<?php
return [

    // ───── Weapons ─────
    [
        'Title' => 'Raptor Claw Knife',
        'Description' => 'A blade carved from the claw of a Velociraptor. Sharp and sacred.',
        'Category' => 'Weapons',
        'Price' => 60.0,
        'Quantity' => 2,
        'IsActive' => true,
        'PublishDate' => '2025-07-10',
<<<<<<< HEAD
        'Item_Image' => null,
=======
        'Item_Image' => 'assets/images/Weps/raptorClawKnife.png'
>>>>>>> 6d0a871561d783c75721bdda7e382102b1748681
    ],
    [
        'Title' => 'Triceratops Horn Spear',
        'Description' => 'A spear reinforced with a polished triceratops horn tip.',
        'Category' => 'Weapons',
        'Price' => 80.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-11',
        'Item_Image' => null,
    ],
    [
        'Title' => 'Obsidian Arrow Set',
        'Description' => 'A set of 10 arrows with obsidian tips and pterosaur feather fletching.',
        'Category' => 'Weapons',
        'Price' => 45.0,
        'Quantity' => 3,
        'IsActive' => true,
        'PublishDate' => '2025-07-12',
        'Item_Image' => null,
    ],
    [
        'Title' => 'Saber-Tooth Bone Club',
        'Description' => 'Heavy club made from a saber-tooth cat’s femur. Devastating in melee.',
        'Category' => 'Weapons',
        'Price' => 55.0,
        'Quantity' => 2,
        'IsActive' => true,
        'PublishDate' => '2025-07-13',
        'Item_Image' => null,
    ],

    // ───── Hunting Equipment ─────
    [
        'Title' => 'Mammoth Jaw Snare Blueprint',
        'Description' => 'Trap design using mammoth jaw bones for crushing effect.',
        'Category' => 'Hunting Equipment',
        'Price' => 35.0,
        'Quantity' => 2,
        'IsActive' => true,
        'PublishDate' => '2025-07-13',
        'Item_Image' => 'assets/images/hunting-materials/MamoothJawSnareBlueprint.png' 
    ],
    [
        'Title' => 'Pterosaur Wing Net Plan',
        'Description' => 'Flexible net design using stretched pterosaur hide.',
        'Category' => 'Hunting Equipment',
        'Price' => 30.0,
        'Quantity' => 4,
        'IsActive' => true,
        'PublishDate' => '2025-07-11',
        'Item_Image' => 'assets/images/hunting-materials/PterosaurWingNetPlan.png'
    ],
    [
        'Title' => 'Spiked Vine Trap Design',
        'Description' => 'Blueprint for hidden traps using thorny jungle vines.',
        'Category' => 'Hunting Equipment',
        'Price' => 25.0,
        'Quantity' => 5,
        'IsActive' => true,
        'PublishDate' => '2025-07-10',
        'Item_Image' => 'assets/images/hunting-materials/Spiketrap.png'
    ],
    [
        'Title' => 'Swamp Pitfall Construction Guide',
        'Description' => 'Instructions for luring prey into quicksand-like traps.',
        'Category' => 'Hunting Equipment',
        'Price' => 40.0,
        'Quantity' => 3,
        'IsActive' => true,
        'PublishDate' => '2025-07-12',
        'Item_Image' => 'assets/images/hunting-materials/SwampPitfallConstructionGuide.png',
    ],

    // ───── Prehistoric Drugs ─────
    [
        'Title' => 'Dilophosaur Venom Extract',
        'Description' => 'Used in rituals and as a paralytic agent in small doses.',
        'Category' => 'Prehistoric Drugs',
        'Price' => 100.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-14',
        'Item_Image' => 'assets/images/prehistoric-drugs/DilophosaurVenomExtract.png',
    ],
    [
        'Title' => 'Jungle Moss Poultice',
        'Description' => 'Reduces infection and promotes rapid wound healing.',
        'Category' => 'Prehistoric Drugs',
        'Price' => 50.0,
        'Quantity' => 4,
        'IsActive' => true,
        'PublishDate' => '2025-07-10',
        'Item_Image' => 'assets/images/prehistoric-drugs/Jungle-Moss-Poultice.jpg',
    ],
    [
        'Title' => 'Hallucinogenic Spore Pouch',
        'Description' => 'Rare spores harvested from glowing cave fungi.',
        'Category' => 'Prehistoric Drugs',
        'Price' => 75.0,
        'Quantity' => 2,
        'IsActive' => true,
        'PublishDate' => '2025-07-11',
        'Item_Image' => 'assets/images/prehistoric-drugs/HallucinogenicSporePouch.png',
    ],
    [
        'Title' => 'Tyrant Root Elixir',
        'Description' => 'Deadly to most, but boosts adrenaline in small doses.',
        'Category' => 'Prehistoric Drugs',
        'Price' => 95.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-12',
        'Item_Image' => 'assets/images/prehistoric-drugs/TyrantRootElixir.png',
    ],

    // ───── Food ─────
    [
        'Title' => 'Dried Megaloceros Meat',
        'Description' => 'Smoky venison from the giant elk of the plains.',
        'Category' => 'Food',
        'Price' => 30.0,
        'Quantity' => 10,
        'IsActive' => true,
        'PublishDate' => '2025-07-11',
        'Item_Image' => null,
    ],
    [   
        'Title' => 'Salted Saber-Tooth Jerky',
        'Description' => 'Tough, salty strips from apex predators.',
        'Category' => 'Food',
        'Price' => 35.0,
        'Quantity' => 6,
        'IsActive' => true,
        'PublishDate' => '2025-07-12',
<<<<<<< HEAD
        'Item_Image' => null,
=======
        'Item_Image' => 'assets/images/food/SaltedSaberToothJerky.png',
>>>>>>> 6d0a871561d783c75721bdda7e382102b1748681
    ],
    [
        'Title' => 'Sun-Baked Fish Slabs',
        'Description' => 'Preserved fish caught from ancient riverbeds.',
        'Category' => 'Food',
        'Price' => 20.0,
        'Quantity' => 8,
        'IsActive' => true,
        'PublishDate' => '2025-07-13',
        'Item_Image' => null,
    ],
    [
        'Title' => 'Fermented Berries',
        'Description' => 'Naturally sweet and mildly intoxicating.',
        'Category' => 'Food',
        'Price' => 18.0,
        'Quantity' => 9,
        'IsActive' => true,
        'PublishDate' => '2025-07-14',
        'Item_Image' => null,
    ],

    // ───── Spices and etc. ─────
    [
        'Title' => 'Crushed Bone Salt',
        'Description' => 'Used to cure meat and cast ritual circles.',
        'Category' => 'Spices and etc.',
        'Price' => 12.0,
        'Quantity' => 10,
        'IsActive' => true,
        'PublishDate' => '2025-07-11',
<<<<<<< HEAD
        'Item_Image' => null,
=======
        'Item_Image' => 'assets/images/spices-etc/crushed-bone-salt.jpg',
>>>>>>> 6d0a871561d783c75721bdda7e382102b1748681
    ],
    [
        'Title' => 'Mammoth Tallow Jar',
        'Description' => 'Fat used for cooking, rituals, or fuel.',
        'Category' => 'Spices and etc.',
        'Price' => 22.0,
        'Quantity' => 5,
        'IsActive' => true,
        'PublishDate' => '2025-07-12',
<<<<<<< HEAD
        'Item_Image' => null,
=======
        'Item_Image' => 'assets/images/spices-etc/mammoth-tallow-jar.jpg',
>>>>>>> 6d0a871561d783c75721bdda7e382102b1748681
    ],
    [
        'Title' => 'Herbal Ash Rub',
        'Description' => 'Spiced ash for meat and ceremonial body painting.',
        'Category' => 'Spices and etc.',
        'Price' => 10.0,
        'Quantity' => 7,
        'IsActive' => true,
        'PublishDate' => '2025-07-13',
<<<<<<< HEAD
        'Item_Image' => null,
=======
        'Item_Image' => 'assets/images/spices-etc/Herbal-Ash-Rub.jpg',
>>>>>>> 6d0a871561d783c75721bdda7e382102b1748681
    ],
    [
        'Title' => 'Smoked Pterosaur Grease',
        'Description' => 'Enhances flavor and believed to ward off spirits.',
        'Category' => 'Spices and etc.',
        'Price' => 15.0,
        'Quantity' => 4,
        'IsActive' => true,
        'PublishDate' => '2025-07-14',
<<<<<<< HEAD
        'Item_Image' => null,
=======
        'Item_Image' => 'assets/images/spices-etc/Smoked-Pterosaur-Grease.jpg',
>>>>>>> 6d0a871561d783c75721bdda7e382102b1748681
    ],
    // ───── Clothing ─────
    [
        'Title' => 'Saber-Tooth Hide Cloak',
        'Description' => 'Worn by chieftains to intimidate rivals.',
        'Category' => 'Clothing',
        'Price' => 70.0,
        'Quantity' => 2,
        'IsActive' => true,
        'PublishDate' => '2025-07-10',
        'Item_Image' => 'assets/images/clothing/Saber-Tooth-Hide-Cloak.jpg',
    ],
    [
        'Title' => 'Feathered Raptor Shawl',
        'Description' => 'Colorful and rare, used by ritual leaders.',
        'Category' => 'Clothing',
        'Price' => 65.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-11',
        'Item_Image' => 'assets/images/clothing/Feathered-Raptor-Shawl.jpg',
    ],
    [
        'Title' => 'Tanned Pterosaur Leathers',
        'Description' => 'Flexible hide perfect for harsh winds.',
        'Category' => 'Clothing',
        'Price' => 40.0,
        'Quantity' => 4,
        'IsActive' => true,
        'PublishDate' => '2025-07-12',
        'Item_Image' => 'assets/images/clothing/Tanned-Pterosaur-Leathers.jpg',
    ],
    [
        'Title' => 'Mammoth Fur Boots',
        'Description' => 'Insulated footwear for arctic hunting.',
        'Category' => 'Clothing',
        'Price' => 50.0,
        'Quantity' => 3,
        'IsActive' => true,
        'PublishDate' => '2025-07-13',
        'Item_Image' => 'assets/images/clothing/Mammoth-Fur-Boots.jpg',
    ],

    // ───── Forging Materials ─────
    [
        'Title' => 'Volcanic Obsidian Slab',
        'Description' => 'Sharpest known material for ancient blades.',
        'Category' => 'Forging Materials',
        'Price' => 55.0,
        'Quantity' => 5,
        'IsActive' => true,
        'PublishDate' => '2025-07-11',
        'Item_Image' => null,
    ],
    [
        'Title' => 'Fossilized Bone Core',
        'Description' => 'Extremely dense, ideal for weapon shafts.',
        'Category' => 'Forging Materials',
        'Price' => 48.0,
        'Quantity' => 6,
        'IsActive' => true,
        'PublishDate' => '2025-07-12',
        'Item_Image' => null,
    ],
    [
        'Title' => 'Ancient Amber Nugget',
        'Description' => 'Conductive in rituals, rumored to hold spirits.',
        'Category' => 'Forging Materials',
        'Price' => 95.0,
        'Quantity' => 2,
        'IsActive' => true,
        'PublishDate' => '2025-07-13',
        'Item_Image' => null,
    ],
    [
        'Title' => 'Meteor Shard',
        'Description' => 'Used by elite blacksmiths for indestructible tools.',
        'Category' => 'Forging Materials',
        'Price' => 150.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-14',
        'Item_Image' => null,
    ],

    // ───── Infrastructure ─────
    [
        'Title' => 'Spiked Mammoth Rib Fence',
        'Description' => 'Imposing bone structure to protect territory.',
        'Category' => 'Infrastructure',
        'Price' => 60.0,
        'Quantity' => 4,
        'IsActive' => true,
        'PublishDate' => '2025-07-10',
        'Item_Image' => 'assets/images/infrastructure/Spiked-Mammoth-Rib-Fence.jpg',
    ],
    [
        'Title' => 'Brontosaur Hide Wall',
        'Description' => 'Enormous, weatherproof tarp made from dinosaur skin.',
        'Category' => 'Infrastructure',
        'Price' => 90.0,
        'Quantity' => 2,
        'IsActive' => true,
        'PublishDate' => '2025-07-11',
        'Item_Image' => 'assets/images/infrastructure/Brontosaur-Hide-Wall.jpg',
    ],
    [
        'Title' => 'Sun-Dried Clay Bricks',
        'Description' => 'Essential for large tribal structures.',
        'Category' => 'Infrastructure',
        'Price' => 25.0,
        'Quantity' => 30,
        'IsActive' => true,
        'PublishDate' => '2025-07-12',
        'Item_Image' => 'assets/images/infrastructure/Sun-Dried-Clay-Bricks.jpg',
    ],
    [
        'Title' => 'Bed Rock Gate',
        'Description' => 'Massive entrance made out of bedrock.',
        'Category' => 'Infrastructure',
        'Price' => 100.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-13',
        'Item_Image' => 'assets/images/infrastructure/Bedrock-Gate.jpg',
    ],

    // ───── Voodoo ─────
    [
        'Title' => 'Tyrannosaur Tooth Charm',
        'Description' => 'Worn to invoke power and fear in enemies.',
        'Category' => 'Voodoo',
        'Price' => 70.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-11',
        'Item_Image' => 'assets/images/voodoo/Tyrannosaur-Tooth-Charm.jpg',
    ],
    [
        'Title' => 'Fossil Eye Pendant',
        'Description' => 'Said to grant sight into other worlds.',
        'Category' => 'Voodoo',
        'Price' => 85.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-12',
        'Item_Image' => 'assets/images/voodoo/Fossil-Eye-Pendant.jpg',
    ],
    [
        'Title' => 'Swamp Voodo Doll',
        'Description' => 'Bound with sticks and bone; used in curses.',
        'Category' => 'Voodoo',
        'Price' => 45.0,
        'Quantity' => 3,
        'IsActive' => true,
        'PublishDate' => '2025-07-13',
        'Item_Image' => 'assets/images/voodoo/Swamp-Voodo-Doll.jpg',
    ],
    [
        'Title' => 'Charred Spirit Idol',
        'Description' => 'Burned before war to summon ancestors.',
        'Category' => 'Voodoo',
        'Price' => 60.0,
        'Quantity' => 2,
        'IsActive' => true,
        'PublishDate' => '2025-07-14',
        'Item_Image' => 'assets/images/voodoo/Charred-Spirit-Idol.jpg',
    ],

    // ───── Ritual Artifacts ─────
    [
        'Title' => 'Blood-Stained Ritual Drum',
        'Description' => 'Played only during moon rites.',
        'Category' => 'Ritual Artifacts',
        'Price' => 80.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-10',
        'Item_Image' => 'assets/images/ritual-artifacts/Blood-Stained-Ritual-Drum.jpg',
    ],
    [
        'Title' => 'Ancient Bone Mask',
        'Description' => 'Used by shamans to enter trance states.',
        'Category' => 'Ritual Artifacts',
        'Price' => 70.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-11',
        'Item_Image' => 'assets/images/ritual-artifacts/Ancient-Bone-Mask.jpg',
    ],
    [
        'Title' => 'Mammoth Skull Totem',
        'Description' => 'Believed to house the soul of a guardian beast.',
        'Category' => 'Ritual Artifacts',
        'Price' => 120.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-12',
        'Item_Image' => 'assets/images/ritual-artifacts/Mammoth-Skull-Totem.jpg',
    ],
    [
        'Title' => 'Bedrock Sacrifice Altar',
        'Description' => 'Transportable slab made for blood offerings.',
        'Category' => 'Ritual Artifacts',
        'Price' => 95.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-13',
        'Item_Image' => 'assets/images/ritual-artifacts/bedrock-sacrifice-altar.jpg',
    ],

    // ───── Pets ─────
    [
        'Title' => 'Juvenile Saber-Tooth Cub',
        'Description' => 'Feral but tamable with patience. Good for guarding.',
        'Category' => 'Pets',
        'Price' => 300.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-12',
        'Item_Image' => 'assets/images/pets/sabertooth-cub.jpg',
    ],
    [
        'Title' => 'Miniature Mammoth Calf',
        'Description' => 'Domesticated from birth. Can carry loads.',
        'Category' => 'Pets',
        'Price' => 500.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-13',
        'Item_Image' => 'assets/images/pets/mammoth-calf.jpeg',
    ],
    [
        'Title' => 'Tamed Raptor Hatchling',
        'Description' => 'Fast, loyal, and deadly when bonded.',
        'Category' => 'Pets',
        'Price' => 450.0,
        'Quantity' => 1,
        'IsActive' => true,
        'PublishDate' => '2025-07-14',
        'Item_Image' => 'assets/images/pets/raptor-hatchling.jpg',
    ],
    [
        'Title' => 'Swamp Glider Lizard',
        'Description' => 'Small flying reptile, good for scouting.',
        'Category' => 'Pets',
        'Price' => 250.0,
        'Quantity' => 2,
        'IsActive' => true,
        'PublishDate' => '2025-07-11',
        'Item_Image' => 'assets/images/pets/Swamp-Glider-Lizard.jpg',
    ],

];
