<?php
return [
    [
        'Username' => 'phantommorphus',
        'Password' => 'phantom06240515543',
        'Email' => 'phantom@primal.market',
        'Alias' => 'ルイくん',
        'TrustLevel' => 10.0,
        'Is_Vendor' => true,
        'Is_Admin'  => true,
        'Is_Banned' => false,
        'Created_At'  => '2025-07-18',
    ],
    [
        'Username' => 'Auditore',
        'Password' => 'requiescat',
        'Email' => '202312060@fit.edu.ph',
        'Alias' => 'Aiden',
        'TrustLevel' => 6.1,
        'Is_Vendor' => false,
        "Is_Admin" => true,
        'Is_Banned' => false,
        'Created_At'  => '2025-03-19',
    ],
    [
        'Username' => 'necrokochou',
        'Password' => 'frieren',
        'Email' => 'necro@primal.market',
        'Alias' => 'Otep',
        'TrustLevel' => 10.0,
        'Is_Vendor' => true,
        'Is_Admin' => true,
        'Is_Banned' => false,
        'Created_At'  => '2025-07-15',
    ],
    [
        'Username' => 'LlenG',
        'Password' => 'bakal',
        'Email' => 'allen@primal.market',
        'Alias' => 'Allen',
        'TrustLevel' => 10.0,
        'Is_Vendor' => true,
        'Is_Admin' => true,
        'Is_Banned' => false,
        'Created_At'  => '2025-07-15',
    ],
    [
        'Username' => 'Cj',
        'Password' => 'thebest',
        'Email' => 'cj@primal.market',
        'Alias' => 'Mother',
        'TrustLevel' => 10.0,
        'Is_Vendor' => true,
        'Is_Admin' => true,
        'Is_Banned' => false,
        'Created_At'  => '2025-07-16',
    ],
    [
        'Username' => 'Ikari',
        'Password' => 'ragebaiter',
        'Email' => 'ikari@primal.market',
        'Alias' => 'Ika',
        'TrustLevel' => 8.0,
        'Is_Vendor' => false,
        'Is_Admin' => false,
        'Is_Banned' => false,
        'Created_At'  => '2025-07-22',
    ],
    [
        'Username' => 'Boris',
        'Password' => 'femboy',
        'Email' => 'boris@primal.market',
        'Alias' => 'Bor Bor',
        'TrustLevel' => 8.9,
        'Is_Vendor' => false,
        'Is_Admin' => false,
        'Is_Banned' => false,
        'Created_At'  => '2025-07-20',
    ],
    [
        'Username' => 'LingLingPing',
        'Password' => 'tra_r6',
        'Email' => 'jm@primal.market',
        'Alias' => 'JM',
        'TrustLevel' => 8.9,
        'Is_Vendor' => false,
        'Is_Admin' => false,
        'Is_Banned' => true,
        'Created_At'  => '2025-07-19',
    ]
];
